App = Ember.Application.create(APP_CONFIG.INIT);

App.Config = Ember.Object.create();

App.TemplateNames = [
  'application',
  'index',
  'storage_survey',
  'sources',
  'sources_source',
  'sources_source_content_type',
  'sync',
  'sync_storage',
  'sync_source',
  'sync_source_content_type_bar',
  'sync_source_content_type_legend'
];

for (var i = 0; i < App.TemplateNames.length; i++) {
  $.ajax({
    url: 'templates/' + App.TemplateNames[i] + '.hbs',         
    async: false,
    success: function (response) {
      Ember.TEMPLATES[App.TemplateNames[i]] = Ember.Handlebars.compile(response);
    }
  });
}

App.Router.map(function() {
  this.route('index', { path: '/' });
  this.route('sources', { path: '/sources' });
  this.route('sync', { path: '/sync' });
});

Ember.Route.reopen({
  events: {
    willTransition: function(transition) {
      this.controllerFor('application').set('targetPath', transition.targetName);

      if (transition.targetName != this.controllerFor('application').get('currentPath')) {
        this.controllerFor('application').handleTransitionStart();
      }
    }
  },

  afterModel: function() {
    // Always scroll to top of window after route transition
    window.scrollTo(0, 0);
    
    this.controllerFor('application').set('targetPath', null);
    this.controllerFor('application').handleTransitionStop();
  }
});

App.ApplicationAdapter = DS.RESTAdapter.extend({
  // Prefix for all API paths generated by Ember Data 
  namespace: 'v1',

  // Ensure all Ember Data API URLs are generated with underscores (eg /v1/storage_survey)
  pathForType: function(type) {
    var underscored = Ember.String.underscore(type)
    return Ember.String.pluralize(underscored);
  }
});

App.ApplicationSerializer = DS.RESTSerializer.extend({
  // Ensure Ember Data expects root variables within API responses to use underscores (eg "storage_survey")
  typeForRoot: function(root) {
    var camelized = Ember.String.camelize(root);
    return Ember.String.singularize(camelized);
  }
});