/* Ember Data Init */

DS.RESTAdapter.reopen({
  // Prefix for all API paths generated by Ember Data 
  namespace: APP_CONFIG.DATA.API_NAMESPACE,

  // Ensure all Ember Data API URLs are generated with underscores (eg /v1/storage_survey)
  pathForType: function(type) {
    var underscored = Ember.String.underscore(type)
    return Ember.String.pluralize(underscored);
  }
});

App.ApplicationSerializer = DS.RESTSerializer.extend({
  // Ensure Ember Data expects root variables within API responses to use underscores (eg "storage_survey")
  typeForRoot: function(root) {
    var camelized = Ember.String.camelize(root);
    return Ember.String.singularize(camelized);
  }
});

App.FixtureAdapter = DS.FixtureAdapter.extend({
});

App.Store = DS.Store.extend({
  adapter: APP_CONFIG.DATA.ADAPTER
});