/* Ember Data Init */

DS.RESTAdapter.reopen({
  // Prefix for all API paths generated by Ember Data 
  namespace: APP_CONFIG.DATA.API_NAMESPACE,

  // Ensure all Ember Data API URLs are generated with underscores (eg /v1/storage_survey)
  pathForType: function(type) {
    var underscored = Ember.String.underscore(type)
    return Ember.String.pluralize(underscored);
  }
});

App.ApplicationSerializer = DS.RESTSerializer.extend({
  // Ensure Ember Data expects root variables within API responses to use underscores (eg "storage_survey")
  typeForRoot: function(root) {
    var camelized = Ember.String.camelize(root);
    return Ember.String.singularize(camelized);
  }
});

App.FixtureAdapter = DS.FixtureAdapter.extend({
});

App.Store = DS.Store.extend({
  adapter: APP_CONFIG.DATA.ADAPTER
});

/* Ember Data bug fix to enable successful saving of one-to-many relationships. 
 *
 * See: http://stackoverflow.com/questions/19093078/ember-data-saving-record-loses-has-many-relationships 
 */
DS.JSONSerializer.reopen({
  serializeHasMany : function(record, json, relationship) {
    var key = relationship.key;
    var relationshipType = DS.RelationshipChange.determineRelationshipType(record.constructor, relationship);

    if (relationshipType === 'manyToNone'
      || relationshipType === 'manyToMany'
      || relationshipType === 'manyToOne') {
      json[key] = Ember.get(record, key).mapBy('id');
    }
  }
});